MDC_Website/urls.py
from django.conf.urls import url
from . import views


app_name = 'MDC_Website'
urlpatterns = [
        url(r'^$|^/$', views.ProductListView.as_view(), name = 'show_products'),
        #url(r'^(?P<category_slug>[-\w]+)/$', views.showProducts, name='show_products_with_category'),
        url(r'register$', views.register, name = 'register'),
        url(r'login$', views.login, name = 'login'),
        url(r'viewProduct/(?P<slug>[-\w]+)', views.viewProduct, name='view_product'),
        url(r'logout$', views.logout, name = 'logout'),
        url(r'account', views.account, name = 'account'),
        url(r'list$', views.product_list, name='product_list'),
        ]

Medical_Device_Company_Website/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 
urlpatterns = [
    url(r'MDC/', include('MDC_Website.urls')),
    url(r'cart/', include('cart.urls')),
    url(r'^admin/', admin.site.urls),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
            document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
        url(r'^$', views.cart_detail, name = 'cart_detail'),
        url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name = 'cart_add'),
        url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name = 'cart_remove'),
            ]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = ((i, str(i)) for i in range(1, 21))

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
            choices = PRODUCT_QUANTITY_CHOICES,
            coerce = int)

    update = forms.BooleanField(
            required = False,
            initial = False,
            widget = forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from MDC_Website.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product = product,
                quantity = cd['quantity'],
                update_quantity = cd['update'])
        return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    product = get_object_or_404(Product ,id = product_id)
    cart = Cart(request)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial = {'quantity': item['quantity'],
            'update': True})

    return render(request, 'cart/cart_detail.html', {'cart': cart})

cart/templates/cart/cart_detail.html
{% extends "MDC_Website/base.html" %}
{% load static %}

{% block title %}
Your shopping cart 
{% endblock %}

{% block content %}
<h1>Your shopping cart </h1>
<table class="class">
	<thead>
		<tr>
			<th>Image</th>
			<th>Product</th>
			<th>Quantity</th>
			<th>Remove</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		{% for item in cart %}
		{% with product=item.product %}
		<tr>
			<td>
				<a href="{{ product.get_absolute_url }}">
					<img src="{% if product.image %}{{ product.image.url}}
					{% else %}{% static "img/no_image.png" %}{% endif %}">
				</a>
			</td>
			<td>{{ product.name }}</td>
			<td>
				<form action="{% url "cart:cart_add" product.id %}" method="post">
					{{ item.update_quantity_form.quantity }}
					{{ item.update_quantity_form.update }}
					<input type="submit" value="Update">
					{% csrf_token %}
				</form>
			</td>

			<td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
			<td class="num">{{ product.price }}</td>
			<td class="num">{{ product.total_price }}</td>
			
		</tr>
		{% endwith %}
		{% endfor %}
		<tr class="total">
			<td>Total</td>
			<td colspan="4"></td>
			<td class="num">${{ cart.get_total_price }}</td>
		</tr>
	</tbody>
	<p class="txt-right">
	<a href="{% url "MDC_Website:show_products" %}" class="button light">Continue shopping</a>
	<a href="#" class="button">Checkout</a>
	</p>
	{% endblock %}