MDC_Website/urls.py
from django.conf.urls import url
from . import views


app_name = 'MDC_Website'
urlpatterns = [
        url(r'^$|^/$', views.ProductListView.as_view(), name = 'show_products'),
        #url(r'^(?P<category_slug>[-\w]+)/$', views.showProducts, name='show_products_with_category'),
        url(r'register$', views.register, name = 'register'),
        url(r'login$', views.login, name = 'login'),
        url(r'viewProduct/(?P<slug>[-\w]+)', views.viewProduct, name='view_product'),
        url(r'logout$', views.logout, name = 'logout'),
        url(r'account', views.account, name = 'account'),
        url(r'list$', views.product_list, name='product_list'),
        ]

Medical_Device_Company_Website/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 
urlpatterns = [
    url(r'MDC/', include('MDC_Website.urls')),
    url(r'cart/', include('cart.urls')),
    url(r'^admin/', admin.site.urls),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
            document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
        url(r'^$', views.cart_detail, name = 'cart_detail'),
        url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name = 'cart_add'),
        url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name = 'cart_remove'),
            ]

MDC_Website/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class AvailableProducts(models.Manager):
    def get_queryset(self):
        return super(AvailableProducts,
                self).get_queryset().filter(product_availability = True)

class Category(models.Model):
    category_name = models.CharField(max_length = 50,
            unique = True,
            db_index = True)
    category_description = models.TextField(max_length = 500,
            db_index = True)
    category_slug = models.SlugField(max_length = 30,
            db_index = True)

    def __str__(self):
        return self.category_name
    
    class Meta:
        ordering = ('category_name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

class Product(models.Model):
    product_name = models.CharField(max_length = 60,
            unique = True,
            db_index = True)
    product_description = models.TextField(max_length = 500,
            db_index = True)
    product_image = models.ImageField(upload_to = 'media', blank = True)
    product_price = models.DecimalField(max_digits = 4, decimal_places = 2)
    product_slug = models.SlugField(max_length = 30)
    product_created_date = models.DateField()
    product_last_updates = models.DateTimeField(auto_now = True)
    product_expire_date = models.DateField(auto_now = False, auto_now_add = False)
    product_available_items = models.PositiveIntegerField()
    product_availability = models.BooleanField(default = False)
    product_category = models.ForeignKey(Category, on_delete = models.CASCADE)
    
    objects = models.Manager()
    available = AvailableProducts()

    def get_absolute_url(self):
        return reverse('MDC_Website:view_product', args = [self.product_slug])

    def __str__(self):
        return self.product_name

    class Meta:
        ordering = ('product_name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

MDC_Website/forms.py
from django import forms

class Register(forms.Form):
    user_name = forms.CharField(label = 'Please enter your name: ', max_length = 100)
    user_password = forms.CharField(label = 'Please enter your password: ', max_length = 100)
    #user_password_confirm = forms.PasswordField(label = 'Password confirm', max_length = 100)
    user_address = forms.CharField(label = 'Please enter your address or use the address generator', max_length = 200)
    user_age = forms.CharField(label = 'Enter your age', max_length = 25)
    user_disease = forms.CharField(label = 'Please enter patient current disease or describe it', max_length = 100)
    user_email = forms.CharField(label = 'Please enter a valid email to keep in touch', max_length = 100)
    user_description = forms.CharField(label = 'Please describe how will you use the product', max_length=70)
    user_chronic_disease = forms.CharField(label = 'Tell us if you have any chronic disease to help our doctors provide best service for you', max_length = 140)
    user_categoury = forms.CharField(label = 'Tell us where will you use the product to help our medical engineers provide best hints for you', max_length = 70)

class Login(forms.Form):
    user_name = forms.CharField(label = "Please enter your user name ", max_length = 100)
    user_password = forms.CharField(label = "Please enter your password", max_length = 100)


class Products(forms.Form):
    department = forms.CharField(max_length = 100)

MDC_Website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from .forms import Register, Login, Products
from django.views.decorators.http import require_http_methods
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from rest_framework import status
from .serializers import ProductSerializer

# Create your views here
#I won't use class until I know how to use tags within it
class ProductListView(ListView):
    queryset = Product.available.all()
    context_object_name = 'products'
    paginate_by = 9
    template_name = 'MDC_Website/product/MDC_Products.html'

#Use this tempo
def showProducts(request, category_slug = None):
    category = None  
    categories = Category.objects.all()
    products = Product.objects.filter(product_availability = True)
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = products.filter(product_category = category)
    return render(request, 'MDC_Website/product/MDC_Products.html', {'products': products,
        'categories': categories,
        'category': category})

#Show product details
def viewProduct(request, slug):
    product = get_object_or_404(Product,
            product_slug = slug,
            product_availability = True)
    cart_product_form = CartAddProductForm()
    return render(request, 'MDC_Website/product/MDC_viewProduct.html', {'product':product,
        'cart_product_form': cart_product_form})


def register(request):
    if request.method == 'POST':
        form = Register(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data['user_name']
            user_password = form.cleaned_data['user_password']
            user_address = form.cleaned_data['user_address']
            user_age = form.cleaned_data['user_age']
            user_disease = form.cleaned_data['user_disease']
            user_email = form.cleaned_data['user_email']
            user_description = form.cleaned_data['user_description']
            user_chronic_disease = form.cleaned_data['user_chronic_disease']
            user_categoury = form.cleaned_data['user_categoury']
            mdc_email = "servertest587@gmail.com"
            user_add = ("INSERT INTO user (u_name, u_password,u_address, u_age, u_disease, u_email,"
                    "u_description, u_chronic_disease, u_categoury) VALUES"
                    " (%s, %s, %s, %s, %s, %s, %s, %s, %s)")
            user_data = (user_name, user_password,user_address, user_age, user_disease,
                    user_email, user_description, user_chronic_disease, 
                    user_categoury)
            cursor = db.databaseConnect(user_add,True, user_data, statement = 'edit')
            msg = "Thx for registration"
            email = smtplib.SMTP(host = 'smtp.gmail.com', port = 587)
            email.starttls()
            email.login(user = 'servertest587', password = 'GMAILTEST587')
            email.ehlo()
            email.sendmail(mdc_email, user_email, msg)
            email.quit()
            welcome_message = "Thx for registration"
        return render(request, 'MDC_Website/MDC_Register.html',
                    {'form':form, 'welcome_message':welcome_message})
    else:
        form = Register()
    return render(request, 'MDC_Website/MDC_Register.html', {'form':form}) 
    
def login(request):
    user_id=''
    user_password = ''
    user_name = ''
    if request.method == 'POST':
        login_form = Login(request.POST)
        if login_form.is_valid():
            user_email = login_form.cleaned_data['user_name']
            user_password = login_form.cleaned_data['user_password']
            login_query = ("SELECT u_name, u_id FROM user WHERE u_email=%s AND u_password=%s")
            email_password = (user_email, user_password)
            data = db.databaseConnect(login_query, True, email_password)
            #check for user email and password
            i = 0
            for u_name, u_id in data:
                i = i + 1
                user_id = u_id
                user_name = u_name
            if i == 1:
                request.session['user_id'] = user_id
                request.session['user_name'] = user_name
                request.session.modified = True
                message = ('Welcome back {}'.format(request.session['user_name']))
                return render(request, 'MDC_Website/MDC_Home.html', {'message':message})
            elif i > 1:
                message = "Duplicate user name and password"
            else:
                message = "Wrong user name or password"
            return render(request, 'MDC_Website/MDC_Login.html', {'login_form':login_form, 'message':message})
    else:
        login_form = Login()
    return render(request, 'MDC_Website/MDC_Login.html',{'login_form':login_form})

def account(request):
    query = "SELECT order_id, p_id FROM user_product WHERE u_id = {}".format(request.session['user_id']) 
    message = "Hello:{} ".format(request.session['user_name'])
    data = db.databaseConnect(query)
    webpage_data = {
            'message':message,
            'products':data}
    return render(request, 'MDC_Website/MDC_Account.html', webpage_data)

def logout(request):
    try:
        del request.session['user_id']
        request.session.flush()
    except KeyError:
        pass
    return render(request, 'MDC_Website/MDC_Home.html')

#REST API
class JSONResponse(HttpResponse):
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)



#To list all products or insert new one
@csrf_exempt
def product_list(request):
    if request.method == 'GET':
        products = Product.objects.all()
        products_serializer = ProductSerializer(products, many = True)
        return JSONResponse(products_serializer.data)
    elif request.method == 'POST':
        new_product = JSONParser().parse(request)
        product_serializer = ProductSerializer(data = new_product)
        if product_serializer.is_valid():
            product_serializer.save()
            return JSONResponse(product_serializer.data, status = status.HTTP_201_CREATED)
    return JSONResponse(products_serializer.errors, status = status.HTTP_400_BAD_REQUEST)

MDC_Website/templates/MDC_Website/MDC_Account.html
{% extends "MDC_Website/MDC_Home.html" %}
{% block content %}
<p>{{message}}</p>
<table>
{% for order_id, product_id in products %}
<tr>
	<th><p>Order ID {{order_id}}</p></th>
	<th><p>Product ID {{product_id}}</p></th>
</tr>
{% endfor %}
</table>
{% endblock %}

MDC_Website/templates/MDC_Website/MDC_Login.html
{% extends 'MDC_Website/MDC_Home.html' %}
{% block title%}Login{% endblock %}
{%block content %}
		<h1>{{ message }}</h1>
		<form action="{% url 'MDC_Website:login' %}" method="post">
			{% csrf_token %}
			<table>
				{% for field in login_form %}
				<tr>
					<th>{{ field.error }}</th>
					<th>{{ field.label_tag }}</th>
					<th>{{ field }}</th>
				</tr>
				{% endfor %}
			</table>
			<input type="submit" value="login"/>
		</form>
		{% endblock %}

MDC_Website/templates/MDC_Website/MDC_Register.html
{% extends "MDC_Website/MDC_Home.html" %}
{% block title %}Login{% endblock %}
		<h1>{{ welcome_message }}</h1>
		{% block content %}
		<center>
			<form action="{% url 'MDC_Website:register' %}" method="post">
				{% csrf_token %}
				<table>
					{% for field in form %}
					<tr>
						<th>{{ field.errors }}</th>
						<th>{{ field.label_tag }}</th>
						<th>{{ field }}</th>
					</tr>
					{% endfor %}
				</table>
				<input type="submit" value="Save">
			</form>
		</center>
		{% endblock %}

MDC_Website/templates/MDC_Website/base.html
{% load static %}
<!DOCTYPE html>
{% load i18n %}
<html lang="{{ LANGUAGE_CODE }}">
<html>
	<head>
		<button id="ajaxButton" type="button">Make a request</button>
	<script>
		(function (){
			var httpRequest;
			document.getElementById("ajaxButton").addEventListener('click', makeRequest);
			function makeRequest(){
				httpRequest = new XMLHttpRequest();
				if(!httpRequest){
					alert("Can't connect to the server");
					return false;
				}
				httpRequest.onreadystatechange = alertcontents;
				httpRequest.open("GET", "127.0.0.1:8000/MDC_Website/list");
				httpRequest.send();
			}
			function alertcontents(){
				try{
					if(httpRequest.readyState == XMLHttpRequest.DONE){
						if(httpRequest.status == 200){
							var response = JSON.parse(httpRequest.responseText);
							alert(response.comutedString);
						}
					}
				}
				catch(e){
					alert("Caught exception: " + e.description);
				}
			}
		})();
	</script>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<title>{% block title %}{% endblock %}</title>
		{% block base_stylesheet %}
		<link rel="stylesheet" type="text/css" href={% static "css/base.css" %} media="screen"/>
		{% endblock %}
		{% block base_js %}
		<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
		<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
		{% endblock %}
		{% block js %}{% endblock %}
	</head>
	
	<body>
		<center>
		<img src="{% static "Design/banner.png" %}"/>
		<H1>Welcome to Medical device company</H1>
		</center>
		<div class="main-header">
			<div class="container">
				<div class="row">
					<div>
						<div class="logo">
							<h1><a href="{% url 'MDC_Website:show_products' %}">
									Medical device company</a>
							</h1>
						</div>
					</div>
					<div>
						<div class="main-menu">
							<ul class="menu">
								<li><a href="{% url 'MDC_Website:show_products' %}">
										Products</a></li>
								<li><a href="{% url 'MDC_Website:login' %}">
										Login</a></li>
								<li><a href="{% url 'MDC_Website:register' %}">
										Register</a></li>
								<li><a href="{% url 'MDC_Website:logout' %}">
										Logout</a></li>
								<li><a href="{% url 'MDC_Website:account' %}">
										Account</a></li>
							</ul>
						</div>
					</div>
		<div id="content">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

MDC_Website/templates/MDC_Website/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
		<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
		<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>